version: '3.3'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ryrZi(Mri2qMJia
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: on-failure
    depends_on:
      - db
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      DB_HOST: db
      DB_PASSWORD: ryrZi(Mri2qMJia
